-- 创建问答应用数据库

CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(20) NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Email TEXT
);

CREATE TABLE IF NOT EXISTS Questions (
    QuestionID INTEGER PRIMARY KEY AUTO_INCREMENT,
    AskerID INTEGER NOT NULL,
    Title TEXT NOT NULL,
    Content TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AskerID) REFERENCES Users(UserID)
);


CREATE TABLE IF NOT EXISTS Answers (
    AnswerID INTEGER PRIMARY KEY AUTO_INCREMENT,
    QuestionID INTEGER NOT NULL,
    AnswererID INTEGER NOT NULL,
    Content TEXT NOT NULL,
    Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QuestionID) REFERENCES Questions(QuestionID),
    FOREIGN KEY (AnswererID) REFERENCES Users(UserID)
);
